services:
  diario:
    build: .
    pull_policy: build
    image: diario-del-dia:latest
    container_name: diario-del-dia
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - diario-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-diario
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    networks:
      - diario-net
    depends_on:
      - diario

networks:
  diario-net:
